In [2]:
import numpy as np

# The basics

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Get deimension
a.ndim
b.ndim

2

In [10]:
a.shape
b.shape

(2, 3)

### Get the type

In [13]:
a.dtype
b.dtype

dtype('int64')

### If we know the values whe want to store, we can specify the object type. In example, we are storing small numbers so there is no need to use 64 bytes for this numbers

In [15]:
a = np.array([1, 2, 3, 4], dtype="int16")
a.dtype

dtype('int16')

### This gets the bytes used to store the object 

In [17]:
a.itemsize

2

# Accessing/changing specific elements, rows, columns, etc.

In [21]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8 , 9, 10, 11, 12, 13, 14]], dtype="int16")
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int16)

In [22]:
# Get specific element [r, c]
a[1, 5]

np.int16(13)

In [24]:
# Get a specific row
a[0, :]

# Get a specific column
a[:, 2]

array([ 3, 10], dtype=int16)

### Getting a little more fancy [startindex:endindex:stepsize]

In [25]:
a[0 , 1:6:2]

array([2, 4, 6], dtype=int16)

In [28]:
a[1, 5] = 20
print(a)

a[:,2] = [1,2]
a

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]], dtype=int16)

In [34]:
b = np.array([[[1,2], [3,4], [5,6], [7, 8]]], dtype="int16")
print(b)
b.shape

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


(1, 4, 2)

In [37]:
# Get an specific element (Workoutside in)
b[0,1,1] = 10
b

array([[[ 1,  2],
        [ 3, 10],
        [ 5,  6],
        [ 7,  8]]], dtype=int16)

# Initializing different types of arrays

### All 0s matrix

In [39]:
np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Al 1s matrix

In [41]:
np.ones((2,3), dtype="int16")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

### Any other number

In [42]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [44]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]], dtype=int16)

### Random decimal numbers

In [45]:
np.random.rand(4,2)

array([[0.56534858, 0.02829986],
       [0.85428132, 0.23927104],
       [0.53273912, 0.17306934],
       [0.1707659 , 0.25799189]])

### Random integer values

In [56]:
np.random.randint(7, size=(3,3))
np.random.randint(-4, 8, size=(3,3))

array([[ 1, -1, -1],
       [ 7, -2,  7],
       [ 7,  2,  1]])

### Identity matrix

In [57]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Repeat the arrays

In [63]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Exercise one: Do this matrix

### My solution

In [76]:
e = np.ones(shape=(5,5), dtype="int8")
for i in range(1, 4):
    e[i][1:4] = 0
e[2][2] = 9
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

### Video solution

In [81]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Be careful when copying arrays, because it has the same problem with pandas, you have to call the method copy otherwise the same 2 variables will be pointing at the same memory location

In [82]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [83]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [87]:
a = np.array([1,2,3,4])
print(a)
print(a+2)
print(a-2)
print(a*2)


[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]


In [88]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

### Take the sin

In [89]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear algebra

In [95]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

# Statistics

In [96]:
stats = np.array([[1,2,3,4], [5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
print("min: ", np.min(stats))
print("max: ", np.max(stats))
print("sum: ", np.sum(stats, axis=1))

min:  1
max:  8
sum:  [10 26]


# Reorganazing arrays

In [109]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before, "\n")

#after = before.reshape(8,1)
after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Vertically stacking vectors

In [110]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Horizontal stacking

In [116]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1, h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [117]:
v1 = np.random.randint(0, 30, size=(3,18))
v1

array([[28, 21, 19, 14, 19, 21, 28, 23, 15,  9, 28, 28,  5,  2, 29, 13,
         1, 24],
       [19,  6, 24, 23,  6,  9, 22,  6, 24,  6, 19, 14,  0,  3, 17, 26,
         6, 25],
       [ 4, 26, 21, 23,  9,  2,  7, 18,  9, 19,  0,  4, 24, 17,  6, 13,
        28, 16]])

### Boolean masking and Advanced indexing

In [120]:
print(v1 > 20)
v1[v1 >=20]

[[ True  True False False False  True  True  True False False  True  True
  False False  True False False  True]
 [False False  True  True False False  True False  True False False False
  False False False  True False  True]
 [False  True  True  True False False False False False False False False
   True False False False  True False]]


array([28, 21, 21, 28, 23, 28, 28, 29, 24, 24, 23, 22, 24, 26, 25, 26, 21,
       23, 24, 28])

### You can index with a list on numpy

In [122]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], dtype="int8")
a[[1,2,8]]

array([2, 3, 9], dtype=int8)