# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.1280, 0.2419, 0.3956, 0.4427, 0.0292, 0.2985, 0.7602],
        [0.0142, 0.9401, 0.2544, 0.4240, 0.1524, 0.8144, 0.0328],
        [0.1843, 0.6749, 0.6982, 0.5318, 0.2492, 0.5876, 0.0173],
        [0.4195, 0.0124, 0.7487, 0.7676, 0.3925, 0.1930, 0.0904],
        [0.2892, 0.2341, 0.2658, 0.9769, 0.9648, 0.5878, 0.3751],
        [0.8761, 0.8264, 0.3253, 0.0836, 0.7495, 0.2700, 0.6609],
        [0.5107, 0.3437, 0.5524, 0.1241, 0.5920, 0.5953, 0.4864]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensor2 = torch.rand(1,7)
print(f"Tensor2: {tensor2.T}")
# Perform matrix multiplication 
tensor @ tensor2.T

Tensor2: tensor([[0.1133],
        [0.7225],
        [0.4744],
        [0.2884],
        [0.9661],
        [0.5218],
        [0.2178]])


tensor([[0.8541],
        [1.5031],
        [1.5442],
        [1.1326],
        [1.9302],
        [1.8836],
        [1.5925]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
a = torch.rand(5,6)
b = torch.rand(6,5)

print(f"Tensor a: {a}")
print(f"Tensor b: {b}")
# Matrix multiply tensors
a @ b

Tensor a: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000],
        [0.1610, 0.2823, 0.6816, 0.9152, 0.3971, 0.8742],
        [0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734]])
Tensor b: tensor([[0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423],
        [0.5263, 0.2437, 0.5846, 0.0332, 0.1387],
        [0.2422, 0.8155, 0.7932, 0.2783, 0.4820],
        [0.8198, 0.9971, 0.6984, 0.5675, 0.8352],
        [0.2056, 0.5932, 0.1123, 0.1535, 0.2417]])


tensor([[0.6367, 1.4343, 1.2440, 1.0009, 1.1310],
        [0.9395, 1.8561, 1.9764, 1.2312, 1.4958],
        [1.0289, 1.7206, 1.3212, 0.8009, 1.1955],
        [1.1438, 2.0357, 1.7907, 0.8843, 1.3124],
        [0.8843, 1.1738, 1.3448, 0.7171, 0.8682]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print("cuda is available" if torch.cuda.is_available() else "cuda is no available, using CPU")

# Create two random tensors on GPU
a = torch.rand(2, 3, device='cuda')
b = torch.rand(2, 3, device='cuda')
print(f"Tensor a: {a}")
print(f"Tensor b: {b}")



cuda is available
Tensor a: tensor([[0.5445, 0.4124, 0.0008],
        [0.7212, 0.5075, 0.7196]], device='cuda:0')
Tensor b: tensor([[0.0047, 0.0667, 0.3504],
        [0.2350, 0.9492, 0.6495]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [26]:
# Perform matmul on tensor_A and tensor_B
a @ b.T

tensor([[0.0303, 0.5199],
        [0.2894, 1.1186]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [32]:
# Find max
print(f"a max: {a.max()}, b max: {b.max()}")
#print(f"a max: {torch.max(a)}, b max: {torch.max(b)}")
# Find min
print(f"a min: {a.min()}, b min: {b.min()}")
#print(f"a min: {torch.min(a)}, b min: {torch.min(b)}")


a max: 0.7212387919425964, b max: 0.9492106437683105
a min: 0.0008202638709917665, b min: 0.0047243740409612656


### 9. Find the maximum and minimum index values of the output of 7.

In [35]:
# Find arg max
print(f"a argmax: {a.argmax()}, b argmax: {b.argmax()}")

# Find arg min
print(f"a argmin: {a.argmin()}, b argmin: {b.argmin()}")

a argmax: 3, b argmax: 4
a argmin: 2, b argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [40]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a = torch.rand(1, 1, 1, 10)
print(a)
# Remove single dimensions
print(a.squeeze())

# Print out tensors and their shapes
print(a.squeeze().shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
